#!/usr/bin/env python3
"""Render the Claude actor of this checkout into a native subagent definition.

Claude Code reads a subagent from `<home>/.claude/agents/<name>.md`: YAML frontmatter with the
identity, the tool surface, the model and the effort level, then the system prompt as the body. The
profile therefore lives here, in the client adapter, and not in the client-neutral role text under
`teams/dev/`, which carries no client keys at all. The body is the same assembly the launcher sends
to an external session, taken from that launcher rather than rebuilt: the role and the user's
simplicity policy, each with the path it came from. The skills of a run are chosen per launch by the
manager and are not part of a standing agent definition.

Ownership is explicit: a generated file starts with the frontmatter marker below, and only such a
file is rewritten, and only when its content changed. A real file somebody else wrote, a symlink of
another tool and anything else under the same name are left alone and reported.
"""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from run_claude_task import IMPLEMENTATION_TOOLS, implementer_instructions


MARKER = "# generated from the harness role source; regenerated by install.sh, edits are lost"
HEADER = "---\n" + MARKER + "\n"
# The implementation profile this pipeline selected; the external launch names the same pair in its
# explicit --model and --effort flags, and the launcher's own default effort stays untouched.
MODEL, EFFORT = "claude-opus-5", "max"


def native_agents(root=ROOT):
    """The Claude actors of this checkout: the canonical role, its native profile and its body."""
    body, sources = implementer_instructions(root)
    role = sources[0]
    return [{"role": role, "body": body,
             "frontmatter": {"name": role["name"], "description": role["description"],
                             "tools": list(IMPLEMENTATION_TOOLS), "model": MODEL, "effort": EFFORT}}]


def render(agent):
    """The native definition of one actor: JSON scalars in the frontmatter, then the instructions."""
    lines = [HEADER.rstrip("\n"), "# source: " + agent["role"]["path"]]
    lines += [key + ": " + json.dumps(value, ensure_ascii=False) for key, value in agent["frontmatter"].items()]
    return "\n".join(lines + ["---", agent["body"].strip(), ""])


def install(target_home, agents=None):
    """Write every Claude actor as a native subagent of the target home; report what each path did."""
    directory = Path(target_home) / ".claude" / "agents"
    lines, written = [], 0
    directory.mkdir(parents=True, exist_ok=True)
    for agent in agents if agents is not None else native_agents():
        destination = directory / (agent["role"]["name"] + ".md")
        content = render(agent)
        if destination.is_symlink():
            lines.append("  пропуск (чужая ссылка): " + str(destination))
            continue
        if destination.exists():
            if not destination.is_file():
                lines.append("  пропуск (уже существует и не файл): " + str(destination))
                continue
            current = destination.read_text(encoding="utf-8", errors="replace")
            if not current.startswith(HEADER):
                lines.append("  пропуск (уже существует и создан не установкой): " + str(destination))
                continue
            if current == content:
                lines.append("  без изменений: " + str(destination))
                continue
            destination.write_text(content, encoding="utf-8")
            lines.append("  обновлен: " + str(destination))
            written += 1
            continue
        destination.write_text(content, encoding="utf-8")
        lines.append("  создан: " + str(destination))
        written += 1
    return lines, written


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target-home", required=True, type=Path,
                        help="Installation root; the agents go to <target-home>/.claude/agents")
    args = parser.parse_args()
    try:
        lines, _ = install(args.target_home)
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
