#!/usr/bin/env python3
"""Render the Codex actors of this checkout into native agent definitions.

Codex loads `$CODEX_HOME/agents/<name>.toml` as a configuration layer for a spawned session: it
requires `name`, `description` and `developer_instructions` and accepts the ordinary config keys
next to them, so the profile of an actor lives here, in the client adapter, and not in the
client-neutral role text under `teams/dev/`. The instructions are the same assembly the launchers
send to a root `codex exec`, taken from those launchers rather than rebuilt: the manager gets its
role together with the absolute paths of this checkout, the reviewer its role with the shared review
criteria and the user's simplicity policy. Nothing here keeps a second copy of a role body.

Permissions written here are the defaults of a generated file, which is not the same guarantee the
launchers give. The reviewer definition asks for `sandbox_mode = "read-only"`, because a review that
can write is not the read-only Check it is asked to be, but Codex reapplies the live sandbox and
approval settings of the session that spawns an agent over what that agent's file says, so a spawned
reviewer can end up with more. The strict run is the external one: `run_codex_review.py` passes
`-a never`, `--sandbox read-only` and `--ignore-user-config` as arguments of the `codex exec` process
it starts itself. The manager definition sets no sandbox and no approval policy at all, so a spawned
manager keeps the permissions of the session that spawned it instead of granting itself more.

Ownership is explicit. A generated file carries a marker on its first line; only a file with that
marker is rewritten, and only when its content actually changed. A real file somebody else wrote, a
symlink of another tool and anything else under the same name are left exactly as they are and
reported, so a second run of the installer changes nothing and never overwrites foreign work.
"""

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from run_codex_manager import DEFAULT_EFFORT as MANAGER_EFFORT, DEFAULT_MODEL as MANAGER_MODEL, manager_instructions
from run_codex_review import DEFAULT_EFFORT as REVIEWER_EFFORT, DEFAULT_MODEL as REVIEWER_MODEL, reviewer_instructions


MARKER = "# generated from the harness role source; regenerated by install.sh, edits are lost"


def native_agents(root=ROOT):
    """The Codex actors of this checkout: the canonical role, its native profile and its instructions."""
    manager_text, manager_role = manager_instructions(root)
    reviewer_text, reviewer_sources = reviewer_instructions(root)
    return [
        {"role": manager_role, "instructions": manager_text,
         # No sandbox_mode and no approval_policy: a spawned manager keeps the permissions of its caller.
         "settings": {"model": MANAGER_MODEL, "model_reasoning_effort": MANAGER_EFFORT}},
        {"role": reviewer_sources[0], "instructions": reviewer_text,
         # A default the spawning session can still override; the launcher is what enforces read-only.
         "settings": {"model": REVIEWER_MODEL, "model_reasoning_effort": REVIEWER_EFFORT,
                      "sandbox_mode": "read-only"}},
    ]


def toml_string(text):
    """One TOML multi-line basic string. Every quote is escaped, so no body can close it early."""
    forbidden = {character for character in text if character < " " and character not in "\n\t"}
    if forbidden:
        raise ValueError("Role text contains control characters TOML cannot carry: %r" % sorted(forbidden))
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return '"""\n' + escaped + '"""'


def render(agent):
    """The native definition of one actor: its identity, its profile and the instructions it is sent."""
    role = agent["role"]
    lines = [MARKER, "# source: " + role["path"],
             "name = " + toml_string(role["name"]),
             "description = " + toml_string(role["description"])]
    lines += [key + " = " + toml_string(value) for key, value in agent["settings"].items()]
    lines += ["developer_instructions = " + toml_string(agent["instructions"]), ""]
    return "\n".join(lines)


def install(target_home, agents=None):
    """Write every Codex actor as a native agent of the target home; report what each path did."""
    directory = Path(target_home) / ".codex" / "agents"
    lines, written = [], 0
    directory.mkdir(parents=True, exist_ok=True)
    for agent in agents if agents is not None else native_agents():
        destination = directory / (agent["role"]["name"] + ".toml")
        content = render(agent)
        if destination.is_symlink():
            lines.append("  пропуск (чужая ссылка): " + str(destination))
            continue
        if destination.exists():
            if not destination.is_file():
                lines.append("  пропуск (уже существует и не файл): " + str(destination))
                continue
            current = destination.read_text(encoding="utf-8", errors="replace")
            if not current.startswith(MARKER):
                lines.append("  пропуск (уже существует и создан не установкой): " + str(destination))
                continue
            if current == content:
                lines.append("  без изменений: " + str(destination))
                continue
            destination.write_text(content, encoding="utf-8")
            lines.append("  обновлен: " + str(destination))
            written += 1
            continue
        destination.write_text(content, encoding="utf-8")
        lines.append("  создан: " + str(destination))
        written += 1
    return lines, written


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target-home", required=True, type=Path,
                        help="Installation root; the agents go to <target-home>/.codex/agents")
    args = parser.parse_args()
    try:
        lines, _ = install(args.target_home)
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
